# quote_model.py
#
# Copyright (C) 2024 Felix GAIDON
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
This module defines the data models for quotes used in the 'daily_quote' project.

It includes base models for quote creation and response, as well as the main
database model for storing quotes with an ID.
"""

from sqlmodel import SQLModel, Field
from typing import Optional


class QuoteBase(SQLModel):
    """
    Base model representing the common structure of a quote.

    Attributes:
        author (str): The author of the quote.
        text (str): The content of the quote.
    """
    author: str
    text: str


class Quote(QuoteBase, table=True):
    """
    Model representing a quote stored in the database.

    Inherits from QuoteBase and adds an 'id' field as the primary key.

    Attributes:
        id (Optional[int]): The unique identifier of the quote. Automatically
        generated by the database.
    """
    id: Optional[int] = Field(default=None, primary_key=True)


class QuoteRequest(QuoteBase):
    """
    Model representing the data required to create a new quote.

    Inherits from QuoteBase without any additional fields. Used in API requests.
    """
    pass


class QuoteResponse(QuoteBase):
    """
    Model representing the data returned when retrieving a quote.

    Inherits from QuoteBase and adds an 'id' field, which represents the unique
    identifier of the quote. Used in API responses.

    Attributes:
        id (int): The unique identifier of the quote.
    """
    id: int
